# Generated by Django 3.2.8 on 2021-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='이미지 파일')),
                ('text', models.TextField(blank=True, null=True, verbose_name='텍스트 인식결과')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '텍스트 인식',
                'verbose_name_plural': '텍스트 인식',
                'db_table': 'ocr_text',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
